/** All Event Bus topics from Phases 1–15 that analytics ingests. */
export const ALL_INGESTED_TOPICS = [
  'masterdata.product.created',
  'masterdata.product.updated',
  'masterdata.product.deactivated',
  'masterdata.customer.created',
  'masterdata.customer.updated',
  'masterdata.customer.deactivated',
  'masterdata.vendor.created',
  'masterdata.vendor.updated',
  'masterdata.vendor.deactivated',
  'finance.journal.posted',
  'finance.journal.reversed',
  'finance.invoice.created',
  'finance.invoice.posted',
  'finance.invoice.paid',
  'finance.invoice.voided',
  'finance.bill.created',
  'finance.bill.posted',
  'finance.bill.paid',
  'finance.bill.voided',
  'finance.payment.recorded',
  'finance.creditmemo.created',
  'finance.creditmemo.posted',
  'plm.document.uploaded',
  'plm.document.revised',
  'plm.document.released',
  'wms.inventory.received',
  'wms.inventory.moved',
  'wms.inventory.shipped',
  'wms.inventory.adjusted',
  'sales.quote.created',
  'sales.quote.sent',
  'sales.quote.accepted',
  'sales.quote.rejected',
  'sales.quote.expired',
  'sales.order.created',
  'sales.order.allocated',
  'sales.order.backordered',
  'sales.order.shipped',
  'mps.workorder.scheduled',
  'mps.workorder.rescheduled',
  'mps.capacity.overloaded',
  'mrp.run.completed',
  'mrp.requisition.created',
  'procurement.po.issued',
  'procurement.po.acknowledged',
  'procurement.asn.received',
  'workforce.shift.assigned',
  'workforce.clock.in',
  'workforce.clock.out',
  'mes.operation.started',
  'mes.operation.completed',
  'mes.cycle.recorded',
  'mes.workorder.verified',
  'qms.inspection.completed',
  'qms.nonconformance.raised',
  'qms.nonconformance.resolved',
  'qms.scrap.reported',
  'cmms.workorder.created',
  'cmms.workorder.completed',
  'cmms.pm.triggered',
  'returns.rma.requested',
  'returns.rma.received',
  'returns.rma.resolved',
] as const;

export type IngestedTopic = (typeof ALL_INGESTED_TOPICS)[number];

export function topicModule(topic: string): string {
  return topic.split('.')[0] ?? 'unknown';
}
