module.exports = {
  displayName: 'api',
  preset: '../../jest.preset.js',
  testEnvironment: 'node',
  setupFiles: ['<rootDir>/jest.setup.js'],
  maxWorkers: 1,
  transform: {
    '^.+\\.[tj]s$': ['ts-jest', { tsconfig: '<rootDir>/tsconfig.spec.json' }],
  },
  moduleFileExtensions: ['ts', 'js', 'html'],
  moduleNameMapper: {
    '^config$': '<rootDir>/../../libs/shared/config/src/index.ts',
    '^database$': '<rootDir>/../../libs/shared/database/src/index.ts',
    '^event-bus$': '<rootDir>/../../libs/shared/event-bus/src/index.ts',
    '^audit$': '<rootDir>/../../libs/shared/audit/src/index.ts',
    '^health$': '<rootDir>/../../libs/shared/health/src/index.ts',
    '^auth$': '<rootDir>/../../libs/shared/auth/src/index.ts',
    '^masterdata$': '<rootDir>/../../libs/masterdata/src/index.ts',
    '^finance$': '<rootDir>/../../libs/finance/src/index.ts',
    '^plm$': '<rootDir>/../../libs/plm/src/index.ts',
    '^wms$': '<rootDir>/../../libs/wms/src/index.ts',
    '^cpq$': '<rootDir>/../../libs/cpq/src/index.ts',
    '^sales$': '<rootDir>/../../libs/sales/src/index.ts',
    '^mps$': '<rootDir>/../../libs/mps/src/index.ts',
    '^mrp$': '<rootDir>/../../libs/mrp/src/index.ts',
    '^procurement$': '<rootDir>/../../libs/procurement/src/index.ts',
    '^workforce$': '<rootDir>/../../libs/workforce/src/index.ts',
    '^mes$': '<rootDir>/../../libs/mes/src/index.ts',
    '^qms$': '<rootDir>/../../libs/qms/src/index.ts',
    '^storage$': '<rootDir>/../../libs/shared/storage/src/index.ts',
    '^trpc$': '<rootDir>/../../libs/trpc/src/index.ts',
  },
  coverageDirectory: '../../coverage/apps/api',
};
